export const PREFIX = `BOARD`;

export const SET_EDIT_MODE = `${PREFIX}//SET_EDIT_MODE`;
export const RESET_EDIT_MODE = `${PREFIX}//RESET_EDIT_MODE`;

export const FETCH_GROUPS_REQUEST = `${PREFIX}//FETCH_GROUPS_REQUEST`;
export const FETCH_GROUPS_COMPLETED = `${PREFIX}//FETCH_GROUPS_COMPLETED`;
export const FETCH_GROUPS_FAILURE = `${PREFIX}//FETCH_GROUPS_FAILURE`;

export const DELETE_GROUP = `${PREFIX}//DELETE_GROUP`;
export const CREATE_GROUP = `${PREFIX}//CREATE_GROUP`;
export const UPDATE_GROUP = `${PREFIX}//UPDATE_GROUP`;
export const TOGGLE_ACTIVE_POINT = `${PREFIX}//TOGGLE_ACTIVE_POINT`;

export const SET_POINT = `${PREFIX}//SET_POINT`;
